# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Wowking
url: https://wowkingah.github.io/
feed: /atom.xml
author_info: <a href="https://wowkingah.github.io">Wowking</a>

myblog:
  gavatar: images/1.jpg
  gpname: Wowking
  github: https://wowkingah.github.io
  coverimgs: []
  postbgimg: []

categories: [SA, DBA]